### PR TITLE
[WIP] New API

### LINKED ISSUE #20: We shouldn't quantize prices to cents by default in discounts
https://github.com/mirumee/prices/blob/master/prices/__init__.py#L350

I propose to add `quantize=True` to apply arguments in discounts and if it is `True` does quantization but not with hard coded value.

In some countries tere are zero decimal places in others can be three of them. I have function for qunatize already:

```python
from babel.core import get_global

def get_quantize_value_for_currency(currency):
    fractions = get_global('currency_fractions')
    try:
        digits_number = fractions[currency][0]
    except KeyError:
        digits_number = fractions['DEFAULT'][0]
    return Decimal(10) ** -digits_number
```

### PR DESCRIPTION
**Pull request by patrys**
Fixes #20

### CODE REVIEW

**Comment by patrys** [comment]
The built-in `sum` uses integer 0 as the default accumulator value so it won't work with a list of Amounts.

**Comment by mociepka** [comment]
Maybe:
```python
price = Price.from_number(net=10, gross=Decimal(10), currency='USD')
```

If float raise error.

**Comment by patrys** [comment]
I'm 👎 on these. Especially introducing `from_number` since there is no `Number` type in Python.

All of these are one-liner `lambda`s and we could keep introducing new ones forever (eg. `Price.from_net_and_tax(net=5, tax=1, currency='USD')`, `Amount.from_dollars(5)`, `Amount.zero_in_currency('GBP')`).

**Comment by mociepka** [comment]
Creating price from int or string will be a common case in my opinion. I agree that word number is not best maybe numeric or digit?

Or maybe default constructor for prices should work on numbers? Like:

```python
price = Price(net=10, gross=Decimal('10'), currency='USD')
price = Price.from_amount(net=Amount(20, 'EUR'), gross=Amount(30, 'EUR'))
```

I think we agree that writing:

```python
import Price, Amount from prices
price = Price(net=Amount(20, 'EUR'), gross=Amount(30, 'EUR'))
```

instead of just:

```python
import Price from prices
price = Price(net=20, gross=30, currency='USD')
```

is less convenient.

**Comment by patrys** [comment]
Again, if you expect to be creating Prices from literals (which really should not be the common case in well written code) then you can write a lambda to aid you with that. I expect the common case to use Amounts in constructor:

```python
@property
def price(self):
    return Price(self.price_net, self.price_gross)
```

**Comment by mociepka** [comment]
That is an example of django world. Prices should be more abstract in my opinion. Your example even show problems with that. You named attributes like `prices` and it looks like you are creating new from two old. Check:

```python
@property
def price(self):
    return Price.from_amount(self.price_net, self.price_gross)
```

It is more verbose.

**Comment by patrys** [comment]
Again, strong 👎.

**Comment by mociepka** [comment]
That is not good argument @patrys . In my opinion `Amount` is great for storing values in DB, and fixes our problems with the `PriceField` but for instance manipulating prices from CVS it will be pain.

`Price(net=10, gross=20, currency='USD')` is simple and clear. `Price` should internally use `Amounts` which is great but why we want to force user to always repeat `Amount`?

**Comment by patrys** [comment]
Please stop the bikeshedding. I am against `Price` constructor accepting _anything_ but `Amount` instances. Creating a `Price` from unqualified integers should not happen often outside of test suites. The whole point of `Amount` is that you _never_ pass around unqualified (ie. currency unknown) numbers.

**Comment by mociepka** [comment]
As I wrote earlier it should use `Amout` internally so all features from `Amout` won't be discarded.
I am thinking about something like that:

```python
class Price(object):

    def __init__(self, net, gross, currency):
        self.net = Amount(net, currency)
        self.gross = Amount(gross, currency)

   @classmethod
   def from_amount():
        if not isinstance(net, Amount) or not isinstance(gross, Amount):
            raise TypeError('Price requires two amounts, got %r, %r' % (net, gross))
        self.net = net
        self.gross = gross
```

**Pull request merged**
